GET http://localhost:8080/simple/test1

###
GET http://localhost:8080/simple/test2

###

GET http://localhost:8080/user/findAll

###
GET http://localhost:8080/user/findOne?id=1

###
GET http://localhost:8080/user/findOneByOrigal?id=1

###
GET http://localhost:8080/user/findAllByOrigal?id=1

###

POST http://localhost:8080/user/
Content-Type: application/json

{
  "id":"2",
  "name":"test3",
  "age":1333
}

###

GET http://localhost:8080/user/1

###
DELETE http://localhost:8080/user/2

###
GET http://localhost:8080/user/

###

PUT http://localhost:8080/user/2
Content-Type: application/json

{
  "name":"test333",
  "age":133
}

###
POST http://localhost:8080/user/valid
Content-Type: application/json

{
  "id":"2",
  "name":"test3",
  "age":133
}

###