###
GET http://localhost:8081/webClient/user/354

###
GET http://localhost:8081/webClient/user/id?id=1

###
POST  http://localhost:8081/webClient/valid/
Content-Type: application/json

{
  "id":"123",
  "name":"321",
  "age":23
}
###
POST http://localhost:8080/mvc/user/valid
Content-Type: application/json

{
  "id":"33",
  "name":"tes666t443",
  "age":22
}
###
GET http://localhost:8081/webClient/user/33

###
GET http://localhost:8081/webClient/user

###
DELETE http://localhost:8081/webClient/354

###
PUT http://localhost:8081/webClient/
Content-Type: application/json

{
  "id": "33",
  "name": "ttt",
  "age": 22
}
###



